### ISSUE TITLE
Linux version 

### ISSUE THREAD

**Issue by dhombios** [saucepleez/taskt#120]
Are there any plans to port this application to Linux?

**Comment by atotalnoob** [comment]
Not really possible, it uses windows apps to control applications. 

The selenium portion could be ported, but then you may as well run selenium without taskt

**Comment by saucepleez** [comment]
@dhombios  The server component for this application is cross-platform, however, the engine used in the client is not.  There are no plans to port the client to Linux as it would require a level of re-work which at this point is not palatable given the team member size.

**Comment by atotalnoob** [comment]
@saucepleez Should've used .NET Core like a real dev

**Comment by saucepleez** [comment]
@atotalnoob  Great idea, let me know when you get done porting this to .net core 👍

**Comment by atotalnoob** [comment]
@saucepleez Once .NET Core 3.0 becomes stable. I ran a port analysis and Taskt is 100% compatible with .NET Core 3.0

**Comment by dhombios** [comment]
I supposed that it was hard to port due to interactions with native functionality of the operating system, but as .net has been open sourced and ported to Linux and this project looks really promising it would be amazing if it becomes cross platform in the future

**Comment by saucepleez** [comment]
@dhombios .net core is currently supporting web apps.  The desktop integration for .net core coming in 3.0 will still only work on Windows.  I guess the main benefit will be desktop apps can use .net core libraries.

In order to port to Linux, you would need to:
- Find a new cross-plat UI library
- Figure out how to handle UI objects and reimplement APIs

To support this, I would say we would need a total rewrite, even with .net core 3.0.  Porting to Linux isnt a bad idea, I just dont know how I would go about it beyond a simple Selenium implementation.
