### ISSUE TITLE
VS 2019 build problem

### ISSUE THREAD

**Issue by burque505** [saucepleez/taskt#129]
Issue: Win7 - Project will not build on VS 2019, May preview
Version: Cloned from GitHub master branch June 16, 2019 at 7:00 a.m. MST
Platform: Win7 Pro 64-bit
Error message: Please see image below.
Steps to reproduce: Open VS 2019, open project, build.

EDIT: Error does **not** occur when building on Win10 Pro, same VS and taskt versions.

![build error](https://user-images.githubusercontent.com/46876254/59564798-5ca58400-9008-11e9-8973-5b87386af4d8.PNG)

**Comment by saucepleez** [comment]
@burque505  Hi, after checking on this, it appears that this control is not available in Windows 7 -- We are currently using AxMsRdpClient9 which requires Windows 8+.  AxMsRdpClient7 may be used instead to build for Windows 7.  We can look at including the Windows 7 control instead as I do not foresee any impact.

RdpClient9:
https://docs.microsoft.com/en-us/windows/desktop/termserv/imsrdpclient9

RdpClient7:
https://docs.microsoft.com/en-us/windows/desktop/termserv/imsrdpclient9

This project uses AxMSTSCLib to add functionality which allows you to automate the process of connecting to machines via RDP in order to keep the display alive, which is primarily an issue when attempting to execute automation on a VM which is not outputting to the display.
