### ISSUE TITLE
machine learning

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#139]
I was wondering what the machine learning would be used for. You make me very happy if you explain.

**Comment by saucepleez** [comment]
The goal of the machine learning will be to allow you to train your robot using samples of data instead of needing to define if/else conditional rules.  You will need to provide sample data supporting whatever process you are trying to make a prediction about. 

Simplest one to start with will be Binary classification: For example, your robot can determine if a piece of text is **spam** or **not spam**.  This extends to anything that can be TRUE or FALSE or existing within 1 of 2 groups.  Given some sample data below, you could try to predict a sentiment -- whether a comment is **positive** or **negative**:

| Label | Text |
| ------------- | ------------- |
| 1  | Very cool project! |
| 1  | I like what you are doing |
| 0  | it is not a good project |
| 1  | I this is a fun open source project |
| 0  | it doesn't work |
| 0  |I would not recommend |
| etc | etc |

Given a dataset like this (except larger and more diverse), you can then take a piece of text (ex. "I like it") and taskt should be able to make a prediction as to whether the text is a 1 or 0 (TRUE or FALSE) with a level of confidence.

**Comment by merveAltili** [comment]
Thank you for informing me. I wish you good work.
