### ISSUE TITLE
Rest api post method-help 

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#142]
![image](https://user-images.githubusercontent.com/27894231/61781309-d6513e80-ae0c-11e9-99e8-4875bc80c3f3.png)
I tested it at the Postman and was able to post. I tried the above picture in the application but it returned as "Bad Request". I'd appreciate it if you could help me.

**Comment by saucepleez** [comment]
Hello,

Your configuration looks correct or what I would expect.  Based on the testing I have done, the following script works fine with a generic testing API.

[api test.txt](https://github.com/saucepleez/taskt/files/3438595/api.test.txt)

What we can do is break out parameters specifically into their own table for configuration.  This is because parameters can have 4 associated fields: Parameter Name, Parameter Value, Content Type, and Parameter Type.  This will give you full and granular control over the parameters so you can tweak the request until the server accepts it.

**Comment by merveAltili** [comment]
How do I split parameters into my own tables specifically for configuration. I'd appreciate it if you help.

**Comment by saucepleez** [comment]
The latest version in DEV has an enhancement for 3.1.0.0.  Are you able to build from the source or do you need a provided binary to test?

![image](https://user-images.githubusercontent.com/5113950/62054653-fe171c80-b1e7-11e9-8508-dd752c8f7565.png)

**Comment by merveAltili** [comment]
![image](https://user-images.githubusercontent.com/27894231/62193295-246fc000-b380-11e9-9fbf-e325b5c2eae8.png)
 An error occurred while upgrading my Restsharp 104.4.0 connection to Restsharp 106.6.9.

**Comment by saucepleez** [comment]
I am not understanding -- the project currently has 106.6.9 installed and latest is 106.6.10.  How are you getting version 104.4.0.0?

**Comment by merveAltili** [comment]
I've established an extra fire base connection to the project. Firebase gives such error in client.GetTaskAsync.

**Comment by merveAltili** [comment]
![image](https://user-images.githubusercontent.com/27894231/62299367-7f3b1180-b47d-11e9-840b-7d9090d72b7b.png)

Where am I making a mistake? The program is still giving an error.

**Comment by atotalnoob** [comment]
Are you building from source or downloading the app

**Comment by merveAltili** [comment]
I founded Devbrachi. I managed to find a job as a postman as a postman, but my work in the painting does not work in Taskt.

**Comment by merveAltili** [comment]
I founded Devbrachi. I managed to send it to the postman, but my work in the painting does not work in Taskt.

**Comment by saucepleez** [comment]
Sorry, can you please restate that?
