### ISSUE TITLE
Taskt Xpath issue

### ISSUE THREAD

**Issue by CHKOTI511** [saucepleez/taskt#167]
I am trying click an element by xpath, which is inside a iframe. How can i do it by Web element action.

**Comment by saucepleez** [comment]
After reviewing this, the functionality was indeed missing.  The logic exists to change windows but not frames.  I have added a new command which enables the ability to switch between multiple frame types:

![image](https://user-images.githubusercontent.com/5113950/70018416-fb408580-1553-11ea-9c72-fe5e036153ef.png)

This is now available in DEV if you are building from source, otherwise, we should be releasing this Friday through a signed build.

**Comment by wladneto** [comment]
You can get Iframe by Xpath (Switch to Frame) first 
![image](https://user-images.githubusercontent.com/15970264/70260593-61edbb00-176f-11ea-8953-3fed3572656c.png)
and next you can click in element inside the Iframe.
