### ISSUE TITLE
calling taskt from c#

### ISSUE THREAD

**Issue by ViennaCoder** [saucepleez/taskt#179]
Hi,
is it possible NOT to use the script but call the different steps directly from C#?
That would be perfect - having full power of C# AND RPA functionality from taskt

Regards

**Comment by saucepleez** [comment]
> Hi,
> is it possible NOT to use the script but call the different steps directly from C#?
> That would be perfect - having full power of C# AND RPA functionality from taskt
> 
> Regards

Hello,

You can import this project directly into another C# project and use whatever you want.  Change the output type of the solution to Class Library from Windows Application and you will get a DLL (taskt.dll).  Importing that DLL into a console application you can call the engine and commands directly:

           //create engine instance
            var tasktEngine = new taskt.Core.Automation.Engine.AutomationEngineInstance();
            
            //create command and execute
            var messageBoxCommand = new taskt.Core.Automation.Commands.MessageBoxCommand();
            messageBoxCommand.v_Message = "hello world!";
            messageBoxCommand.RunCommand(tasktEngine);
            
            //message box will be displayed

You can also create variables, etc.

            //add variable
            var scriptVariable = new taskt.Core.Script.ScriptVariable()
            {
                VariableName = "vStatement",
                VariableValue = "This is from a variable!"
            };

            tasktEngine.VariableList.Add(scriptVariable);

            //create command and execute
            messageBoxCommand = new taskt.Core.Automation.Commands.MessageBoxCommand();
            messageBoxCommand.v_Message = "hello world! {vStatement}";
            messageBoxCommand.RunCommand(tasktEngine);

            //outputs "hello world! This is from a variable!"

The commands must run under an automation engine instance, because the automation engine instance tracks the opened application instances, variables, and other environment details between commands and during invocation.

Every automation command will expose a method "RunCommand" which is called to execute the command.
