### ISSUE TITLE
Variables strip leading zeros

### ISSUE THREAD

**Issue by AlanGould** [saucepleez/taskt#206]
Is there any way of preserving leading zeros in variables?  Two examples:

Firstly, simply setting a variable
```
New Variable [Assign '01234' to New Variable 'test']
Show Message [Message: {test}]
```
Outputs: `1234`

Secondly (my specific use case), when using either Web Browser Element Action -> Get Text or returning a text() value with Execute Script.

For example: `<div id="test">01234</div>`
Web Browser -> Execute Script: `return $("#test").text();`
Variable value =`1234`

Thanks

**Comment by saucepleez** [comment]
Hello,

This is due to the default current engine settings of your client.  To explain why this is happening, variables by default are set to automatically calculate when output (displayed).  For example, you could set the variable as `2 + 1` and the Message Output would show `3`.  You can modify this behavior at the client or task level.

For the client level:

 Go to **Options > Settings Manager** and select the "Automation Engine".  Uncheck 'Calculate Variables Automatically".

For the task level:

Expand **Engine Commands** and select "Set Engine Preference" command. In the parameter type dropdown you can Select "Disable Automatic Calculations".  In order to re-enable the functionality for the executing task, you must add the same command and select "Enable Automatic Calculations".

**Comment by AlanGould** [comment]
Ah awesome.  That makes sense - nice feature!  Thanks for your help.
