### ISSUE TITLE
calculate with variables

### ISSUE THREAD

**Issue by taktd1130** [saucepleez/taskt#79]
The last line number is obtained by the command of the last line and assigned to the variable
I will try to loop until the number of lines from the last line to the second line
I set the variable as follows, but it did not work.

[lastrow] -2

Can not calculate with variables?

**Comment by saucepleez** [comment]
Yes, variables can perform basic calculations.  You will need to use the **Set Variable** command which performs the actual math operation.  

Math Operations otherwise are not performed automatically.  So, you will need to exclusively call the **Set Variable** Command and in it assign [lastrow] - 2.  Then in your command, you can simply use the variable.

**Comment by taktd1130** [comment]
If you set the numerical value to the variable with the Set Variable command, we can confirm that we can do the calculation.
The problem that we could not calculate this time by substituting the value obtained by the command into the variable and calculating it.
For example, suppose you have created the following script.
![image](https://user-images.githubusercontent.com/24951834/47957246-c4690a80-dff5-11e8-8ee8-353cc9e1ec8c.png)

Show lastrow value
![image](https://user-images.githubusercontent.com/24951834/47957251-dba7f800-dff5-11e8-8e8b-90fe7d2955f5.png)

Display the value of lastrow2
![image](https://user-images.githubusercontent.com/24951834/47957267-f5493f80-dff5-11e8-8885-223b10b6c3b7.png)

I want to display 8 as the calculation result here.

**Comment by taktd1130** [comment]
I ran the script I received.

The value of the last line. This is OK.
![image](https://user-images.githubusercontent.com/24951834/47957660-ae5f4800-dffd-11e8-87a7-16936e1ca0e5.png)

The value of vLastRow2. An expression was output and the calculation result was not output.
![image](https://user-images.githubusercontent.com/24951834/47957667-be772780-dffd-11e8-91a4-06f5fcf4f81d.png)

version information.
![image](https://user-images.githubusercontent.com/24951834/47957669-d5b61500-dffd-11e8-946e-73ee58f140df.png)

**Comment by saucepleez** [comment]
Ok, I was unable to replicate, but I think I have found the issue -- the **.ConvertToUserVariable()** method handles converting the text into the value of the variable automatically.  This was originally done to make the concepts of variables 'easy to use' -- you do not need to understand types like strings, ints, doubles, etc, its all managed under the hood.

This has presented a problem now as the engine is automatically deciding the type of data based on the pattern of the data itself.  To do this, it does the following checks:

- If the text is a valid date -> Do not perform a calculation
- If the text starts with an operand (+,-,*,/) -> Do not perform a calculation
- All other scenarios will attempt a calculation and return the new value is successful otherwise keep the existing value

The Problem here is that "10 - 2" after conversion looks like a date type to the engine -- it is parsed successfully as a Date and therefore the engine determines a calculation is not needed (or else it would literally be doing (10 - 2 - 2018).  The fix will be two-fold:

- Remove the Date Check - Dates have their own calculation command now so the **Set Variable** will no longer be needed for date calculations

- Add **Math Calculation** command to allow for explicit calculations

After this, lets re-test and see if the changes help.

**Comment by saucepleez** [comment]
Ok, I was unable to replicate, but I think I have found the issue -- the **.ConvertToUserVariable()** method handles converting the text into the value of the variable automatically. This was originally done to make the concepts of variables 'easy to use' -- you do not need to understand types like strings, ints, doubles, etc, its all managed under the hood.

This has presented a problem now as the engine is automatically deciding the type of data based on the pattern of the data itself. To do this, it does the following checks:

- If the text is a valid date -> Do not perform a calculation
- If the text starts with an operand (+,-,*,/) -> Do not perform a calculation
- All other scenarios will attempt a calculation and return the new value is successful otherwise keep the existing value

The Problem here is that "10 - 2" after conversion looks like a date type to the engine -- it is parsed successfully as a Date and therefore the engine determines a calculation is not needed (or else it would literally be doing (10 - 2 - 2018).

The fix to try will be to remove the Date Check - Dates have their own calculation command now so the **Set Variable** will no longer be needed for date calculations

After this, lets re-test and see if the changes help.

**Comment by saucepleez** [comment]
I have published a new testing build.  Can you see if the issue is resolved?

https://github.com/saucepleez/taskt/releases/tag/v2.1.0.0-pre2

**Comment by taktd1130** [comment]
Thank you for your immediate response.
All problems have been solved.
This issue is okay even if you close it.

**Comment by saucepleez** [comment]
glad it works!
